env:
  global:
    - _AGAVE_APISERVER="https://api.sd2e.org"
    - _AGAVE_USERNAME="sd2etest"
    - _AGAVE_APIKEY="wzJw3V7Djv_iyzge6lvwyIFyxEMa"
    - _AGAVE_CLIENT_NAME="travisci-agave-files"
    - AGAVEURI=agave://data-sd2e-community/sample/fcs-tasbe/fcs-etl-reactor-example
    - JOBDIR=tmpdir
sudo: required
language: python
python:
  - '2.7'
services:
  - docker
before_install:
  - pip install git+https://github.com/TACC/agavepy.git@develop
  - docker pull fcs-etl:build || true
  - docker build --pull -t fcs-etl:travis -f Dockerfile .
before_script:
  - python scripts/agave-files-sync.py -r ${AGAVEURI} . && mv fcs-etl-reactor-example ${JOBDIR}
script:
  - echo "Get help?"
  - docker run fcs-etl:travis python /src/fcs.py --help
  - echo "Run internal unit tests in container"
  - docker run fcs-etl:travis python /src/test_scratch.py
  - echo "Run functional test in container"
  - docker run -v $JOBDIR:/data -e "CYT_CONFIG=/data/cytometer_configuration.json" -e "PROC_CONTROL=/data/process_control_data.json" -e "EXP_DATA=/data/experimental_data.json" -e "COLOR_MODEL_PARAMS=/data/color_model_parameters.json" -e "ANALYSIS_PARAMS=/data/analysis_parameters.json" fcs-etl:travis
after_script:
  - docker images
