sudo: required

language: python

services:
  - docker

before_install:
  - docker --version
  - cd src && docker build -t fcs-etl .
  - docker run fcs-etl python /src/fcs.py --help

script:
  python /src/fcs.py --help
