env:
  global:
    - _AGAVE_TENANT="sd2e"
    - _AGAVE_APISERVER="https://api.sd2e.org"
    - _AGAVE_USERNAME="sd2etest"
    - _AGAVE_APIKEY="wzJw3V7Djv_iyzge6lvwyIFyxEMa"
    - _AGAVE_CLIENT_NAME="travisci-agave-files"
    - _REGISTRY_USERNAME="sd2etest"
    - AGAVEURI=agave://data-sd2e-community/sample/fcs-tasbe/fcs-etl-reactor-example
    - JOBDIR=fcs-etl-reactor-example
    - CONTAINER_REPO="fcs-etl"
    - CONTAINER_TAG="test"
sudo: required
language: python
python:
  - '2.7'
services:
  - docker
before_install:
  - pip install git+https://github.com/TACC/agavepy.git@develop configparser
  - sudo apt-get -qq update 
  - sudo apt-get install -y jq
  - bash scripts/install_configure_cli.sh
  - export PATH=$PATH:$HOME/sd2e-cloud-cli/bin
  - apps-build-container -O "${_REGISTRY_USERNAME}" --image "${CONTAINER_REPO}" --tag "${CONTAINER_TAG}"
before_script:
  - python scripts/agave_files_sync.py -r ${AGAVEURI} .
script:
  - bash tests/run_functional_test.sh "${_REGISTRY_USERNAME}/${CONTAINER_REPO}:${CONTAINER_TAG}"
  - apps-deploy -T -O ${_REGISTRY_USERNAME} --image "${CONTAINER_REPO}"" --tag "${CONTAINER_TAG}"
  - bash tests/run_tacc_cloud_job.sh
after_script:
  - docker images
