sudo: required

language: python

services:
  - docker

before_install:
  - docker --version
  - docker build --pull -t fcs-etl .

script:
  - docker run fcs-etl python /src/fcs.py --help
  - docker run fcs-etl python /src/test_scratch.py

after_script:
  - docker images
